# pip install -r docs/requirements.txt
# mkdocs serve

site_name: gradle refreshVersions
site_url: https://jmfayard.github.io/refreshVersions/
repo_name: refreshVersions
repo_url: https://github.com/jmfayard/refreshVersions
site_description: "Life is too short to google for dependencies and versions"
site_author: jmfayard LouisCAD
remote_branch: gh-pages
#edit_uri: ""

extra:
  link:
    playground: https://github.com/LouisCAD/kotlin-libraries-playground
    site: https://jmfayard.github.io/refreshVersions
    github: https://github.com/jmfayard/refreshVersions
    master: https://github.com/jmfayard/refreshVersions/blob/master
    issues: https://github.com/jmfayard/refreshVersions/issues
    gradlePluginPortal: https://plugins.gradle.org/plugin/de.fayard.refreshVersions
    slack: https://app.slack.com/client/T09229ZC6/CP5659EL9
  version:
    gradle: 6.7
    refreshVersions: '0.9.7'
    refreshVersionsDev: '0.9.7-dev-001'
  badge:
    mit: https://img.shields.io/github/license/mashape/apistatus.svg
    slack: https://img.shields.io/static/v1?label=kotlinlang&message=gradle-refresh-versions&color=brightgreen&logo=slack
    refreshVersions: https://img.shields.io/maven-metadata/v/https/plugins.gradle.org/m2/de.fayard/refreshVersions/de.fayard.refreshVersions.gradle.plugin/maven-metadata.xml.svg?label=refreshVersions
    pr: https://img.shields.io/github/issues-pr-raw/jmfayard/refreshVersions

copyright: 'Copyright &copy; 2020 jmfayard'

theme:
  name: 'material'
## TODO: we need a logo
#  favicon: images/icon-square.png
#  logo: images/icon-square.png
  palette:
    primary: 'teal'
    accent: 'white'

extra_css:
  - 'app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed
  - tables

nav:
  - 'Overview': index.md
  - 'Setup': setup.md
  - 'Adding Dependencies': adding-dependencies.md
  - 'Updating Dependencies': updating-dependencies.md
  - 'Migration': migration.md
  - 'Common Errors': faq.md
  - 'Change Log': CHANGELOG.md
  - 'Contributing': CONTRIBUTING.md
  - 'Code of Conduct': code_of_conduct.md

plugins:
  - search
  - markdownextradata: {}
