# Global settings applied to the whole site.
#
# Read the friendly documentation
# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file


[build]
  base    = "website"
  publish = "build/docs/orchid"
  command = "./gradlew orchidBuild -Penv=prod"