# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Check build and tests of plugins and samples
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'plugins/**'
      - 'sample-kotlin/**'
      - 'sample-groovy/**'
      - '!**.md'
      - '!.editorconfig'
      - '!**/.gitignore'
      - '!**.adoc'
      - '!docs/**'
  push:
    branches:
      - main
    paths:
      - 'plugins/**'
      - 'sample-kotlin/**'
      - 'sample-groovy/**'
      - '!**.md'
      - '!.editorconfig'
      - '!**/.gitignore'
      - '!**.adoc'
      - '!docs/**'
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Check plugins and publish them to MavenLocal
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: plugins/gradlew
          build-root-directory: plugins
          arguments: check publishToMavenLocal --stacktrace
      - name: Check sample-kotlin
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: sample-kotlin/gradlew
          build-root-directory: sample-kotlin
          arguments: check --stacktrace
      - name: Check sample-groovy
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: sample-groovy/gradlew
          build-root-directory: sample-groovy
          arguments: check --stacktrace
      - name: Check sample-multi-modules
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: sample-multi-modules/gradlew
          build-root-directory: sample-multi-modules
          arguments: check --stacktrace
      - name: Check sample-kotlin-js
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: sample-kotlin-js/gradlew
          build-root-directory: sample-kotlin-js
          arguments: check --stacktrace
