# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Check build and tests of plugins and samples
on:
  pull_request:
    paths:
      - 'refreshVersions/**'
      - 'dependencies/**'
      - 'sample-kotlin/**'
      - 'sample-groovy/**'
      - '!**.md'
      - '!.editorconfig'
      - '!**/.gitignore'
      - '!**.adoc'
  push:
    branches:
      - develop
      - master
    paths:
      - 'refreshVersions/**'
      - 'dependencies/**'
      - 'sample-kotlin/**'
      - 'sample-groovy/**'
      - '!**.md'
      - '!.editorconfig'
      - '!**/.gitignore'
      - '!**.adoc'
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: refreshVersions
          build-root-directory: refreshVersions
          arguments: check publishToMavenLocal --stacktrace
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: dependencies
          build-root-directory: dependencies
          arguments: check publishToMavenLocal --stacktrace
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: sample-kotlin
          build-root-directory: sample-kotlin
          arguments: check --stacktrace
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: sample-groovy
          build-root-directory: sample-groovy
          arguments: check --stacktrace
