# # https://github.com/marketplace/actions/gradle-build-action
name: Check sample-android
on:
  push:
    branches:
      - main
    paths:
      - 'sample-android/**'
      - '!**.md'
      - '!**.adoc'
      - '!.editorconfig'
      - '!**/.gitignore'
  workflow_dispatch:
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: plugins/gradlew
          build-root-directory: plugins
          arguments: check publishToMavenLocal --stacktrace
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: sample-android/gradlew
          build-root-directory: sample-android
          arguments: refreshVersions --stacktrace
      - uses: gradle/gradle-build-action@v2
        with:
          wrapper-directory: sample-android/gradlew
          build-root-directory: sample-android
          arguments: check --stacktrace
