# .github/workflows/gradle-build-pr.yml
# https://github.com/marketplace/actions/gradle-command
name: sample-android
on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'sample-android/**'
      - '!**.md'
      - '!**.adoc'
      - '!.editorconfig'
      - '!**/.gitignore'
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: refreshVersions
        build-root-directory: refreshVersions
        arguments: publishToMavenLocal
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: dependencies
        build-root-directory: dependencies
        arguments: publishToMavenLocal
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: sample-android
        build-root-directory: sample-android
        arguments: refreshVersions
